name: Weekly

on:
  # Run every Sunday at midnight.
  schedule:
    - cron: 0 0 * * 0
  # Allow running manually.
  workflow_dispatch:

env:
  # Force colorful output, even though we're running in Github Actions.
  CARGO_TERM_COLOR: always

jobs:
  test-windows-rs-versions:
    name: Test with windows-rs ${{ matrix.windows-rs }}
    runs-on: windows-2019
    strategy:
      # One version failing should not cancel another.
      fail-fast: false
      matrix:
        windows-rs: [0.57.0, 0.56.0, 0.54.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Consider checking out MSRV
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Pin windows-rs version to ${{ matrix.windows-rs }}
        run: |
          cargo update windows --precise ${{ matrix.windows-rs }}

      # TODO: Cache files using Swatinem/rust-cache@v2

      - name: Test accesskit_windows
        run: cargo test -p accesskit_windows
